version: '2'
services:

  server-dist:
    restart: unless-stopped
    build:
      context: ./server/dist
      dockerfile: Dockerfile.scratch
    ports:
     - "61650:61650"
    environment:
     - ELASTICSEARCH_URL=elastic1x:9200
     - REDIS_URL=redis:6379
     - PORT=61650
    volumes:
     - "./server:/app/github.com/roscopecoltran/aor-entities/server"
    networks:
     - front

  admin-dist:
    restart: unless-stopped
    build: 
      context: ./client/admin/build
      dockerfile: Dockerfile.alpine
    ports:
    - "80:80"
    volumes:
    - "./admin:/app/github.com/roscopecoltran/aor-entities/admin"
    networks:
     - front

  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  # REPOSITORY               TAG                 SIZE
  # blacktop/elasticsearch   latest              117MB
  # blacktop/elasticsearch   6.0                 117MB
  # blacktop/elasticsearch   5.6                 124MB
  # blacktop/elasticsearch   5.5                 123MB
  # blacktop/elasticsearch   5.4                 123MB
  # blacktop/elasticsearch   5.3                 123MB
  # blacktop/elasticsearch   x-pack              691MB
  # blacktop/elasticsearch   geoip               150MB
  # blacktop/elasticsearch   5.2                 150MB
  # blacktop/elasticsearch   5.1                 149MB
  # blacktop/elasticsearch   5.0                 148.4MB
  # blacktop/elasticsearch   2.4                 116MB
  # blacktop/elasticsearch   kopf                122MB
  # blacktop/elasticsearch   2.3                 139.1MB
  # blacktop/elasticsearch   1.7                 142.7MB
  # NOTE:
  # - tag x-pack is the same as tag latest, but includes the x-pack, the ingest-geoip and the ingest-user-agent plugin.
  # - tag geoip is the same as tag latest, but includes the ingest-geoip and the ingest-user-agent plugin.
  # - tag kopf is the same as tag 2.4, but includes the kopf plugin.
  es-master:
    restart: unless-stopped
    image: blacktop/elasticsearch
    command: master
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - IPC_LOCK
    volumes:
    # - data:/usr/share/elasticsearch/data
    - ./shared/data/idx/elastic:/usr/share/elasticsearch/data
    networks:
    - elastic

  ####################################
  # ELASTICSEARCH CLIENT/INGEST NODE #
  ####################################
  es-client:
    restart: unless-stopped
    image: blacktop/elasticsearch:kopf
    command: client
    ports:
    - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
    - IPC_LOCK
    links:
    - es-master:elastic-master
    networks:
    - elastic

  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: kibana
    ports:
    - "5601:5601"
    links:
    - es-client:elasticsearch
    networks:
    - elastic

  redis:
    restart: unless-stopped
    image: redis:3.2.11-alpine
    container_name: redis
    networks:
    - front

  postgres:
    restart: unless-stopped
    image: postgres:9.6.6-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: aor-entities
      POSTGRES_PASSWORD: aor-password # to change in prod
      POSTGRES_DBNAME: aor-entities
      POSTGRES_DBUSER: aor
      POSTGRES_DBPASS: aor-dbpassword
    ports:
    - "5432:5432"
    volumes:
    - ./shared/data/db/postgres:/var/lib/postgresql/data
    networks:
    - front

#############################
# ELASTICSEARCH DATA VOLUME #
#############################
volumes:
  data:

################################
# ELASTICSEARCH BRIDGE NETWORK #
################################
networks:
  elastic:
    driver: bridge
  front:
    driver: bridge